### ISSUE TITLE
Decentralized Hub for News Fact-Checking #8 (Resubmitted)

### ISSUE THREAD

**Issue by dmitry-christie** [Blockternship/projects#22]
Hello everyone, we're Dmitry and Alvaro. We are both developers, working from Portugal and Spain respectively. This is our first 'hands-on' experience with blockchain and we're very excited.

**Overview**
Fake News is running rampant. Everyday we are bombarded with dubious claims and questionable statistics. With the emergence of blockchain technologies, we have the power to work as a community to verify the authenticity of the news we read, hear, and watch.

Our goal is to create an open source dapp where users can pose questions (and attach references for those questions) based on online news to the community and have verified users determine the veracity of that news and provide sources to support their answers. We would use 'BrightID score' or Telegram Passport authentication to ensure that the community is not abused. The use of a person’s real identity incentivizes them to give truthful answers and provide valid sources for their claims. Other users will also be able to determine whether the answers given are accurate, dispute answers, and give follow-ups to answers.

Each community member that actively participates will also have a reputation within the platform and the more they accurately answer questions and provide accurate sources, the higher their reputation will be.

**Next Steps**
We're looking into best ways to build it, if possible, using Aragon tools. We're still working on the UI. We're also considering tokenisation, to make it possible to assign a bounty for a correct answer to a question and make it so, that the bounty can be increased by other people who're interested in this question. Naturally, getting the maths right will be a challenge.

If you've ideas and suggestions, reach us out on Telegram @dreamitry and @alvararo

**Comment by dmitry-christie** [comment]
@YalorMewn Done :)

**Comment by YalorMewn** [comment]
@geleeroyale would you please add a status bounty here too :)

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x396fb9690d76e85e1b3f66f82f84e7447d61110e](https://etherscan.io/address/0x396fb9690d76e85e1b3f66f82f84e7447d61110e)
![QR Code](https://openbounty.status.im/qr/Blockternship/projects/bounty/22/f377b4a1558797c7d288b18530428214d1dff92318cfe40dc474b391194854c9/qr.png)
Network: Mainnet
To claim this bounty sign up at [https://openbounty.status.im](https://openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send ETH or ERC20/ERC223 tokens to the contract address.
